items:
  oneOf:
  - allOf:
    - $comment: 'When using the list representation, ''class'' is required to indicate
        which one is being represented.

        When using the mapping representation, ''class'' is optional since it''s the
        key, but it must match by name.

        '
      required:
      - class
    - $ref: bblocks://ogc.cwl.v1_2_1.CWLHintsItem
  - $ref: bblocks://ogc.cwl.v1_2_1.CWLImport
title: CWLHintsList
type: array
